config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get 'notifications/index'
  get 'homes/top'
  get 'homes/about'
  devise_for :users
  get "users/my_page"=>"users#index"
  resources :users, only: [:edit, :show, :update] do
    member do
      get :user_join
    end
  end
  resources :rooms
  resources :messages
  resources :events do
  collection do
    get 'search'
   end
  end

  resources :event_joins, only: [:create, :update]
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  has_many :events
  has_many :event_joins
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!, only: [:show]
  def index
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def show
    @user = User.find(params[:id])
    @currentRoomUser = RoomUser.where(user_id: current_user.id)  #current_userが既にルームに参加しているか判断
    @receiveUser = RoomUser.where(user_id: @user.id)  #他の@userがルームに参加しているか判断

    unless @user.id == current_user.id  #current_userと@userが一致していなければ
      @currentRoomUser.each do |cu|    #current_userが参加していルームを取り出す
        @receiveUser.each do |u|    #@userが参加しているルームを取り出す
          if cu.room_id == u.room_id    #current_userと@userのルームが同じか判断(既にルームが作られているか)
            @haveRoom = true    #falseの時(同じじゃない時)の条件を記述するために変数に代入
            @roomId = cu.room_id   #ルームが共通しているcurrent_userと@userに対して変数を指定
          end
        end
      end
      unless @haveroom    #ルームが同じじゃなければ
        #新しいインスタンスを生成
        @room = Room.new
        @RoomUser = RoomUser.new
        #//新しいインスタンスを生成
      end
    end
     @events=Event.where(user_id: @user.id).where('date_from >= ?', Date.today)
     @event_joins = EventJoin.where(user_id: current_user.id, status: nil)
     @notifications = @user.passive_notifications.where(checked: nil).where.not(visitor_id: @user.id)

     # @event_joins_future = EventJoin.where(user_id: current_user.id, status: nil)
  end


  def user_join
    joined_users= EventJoin.where(event_id: params[:event_id]).where.not(status: "キャンセル").or(EventJoin.where(event_id: params[:event_id]).where(status: nil)).pluck(:user_id)
    @users=User.find(joined_users)
  end


  private
  def user_params
    params.require(:user).permit(:name, :detail, :image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<div>
 <%= link_to user_path(visitor) do %>
     <%= visitor.name %>さんが
 <% end %>
 <% if notification.action=='dm' %>
    あなたにDMを送りました
 <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col font-weight-bold h4 mt-5 text-left">
  編集ページ
  </div>
 </div>
 <%= form_with model:@user,url: user_path(@user.id), local:true do |f| %>
 <div class="row">
  <div class="col-4 mt-5 text-left">
  <dl>
   <dt><%= attachment_image_tag @user, :image, format: 'png', size: "500x400", class: "icon_image"%></dt>
   <dd class="mt-2"><%= f.file_field :image %></dd>
  </dl>
  </div>

  <div class="col mt-5 text-left">
   <dl>
    <dt class="mb-5">
     <%= f.label "氏名" %>
     <%= f.text_field :name, autofocus: true %>
    </dt>
    <dt>
     <%= f.label "自己紹介" %>
     <%= f.text_area :detail, autofocus: true,size: "30x5" %>
    </dt>
   </dl>
  </div>
 </div>
 <div class="row">
  <div class="col-8 mt-5 text-right">
   <%= f.submit '変更を保存' %>
  </div>
 </div>
 <% end %>

</div>

app/views/users/index.html.erb
マイページ

app/views/users/show.html.erb
<div class="container ">
 <div class="row mt-5 font-weight-bold h4">
  <div class="col mb-5">
    <%= @user.name %>さんの詳細ページ
  </div>
 </div>
 <div class="row text-center mt-4">
  <div class="col-6 text-right">
    <%= attachment_image_tag @user, :image, format: 'png', size: "500x400", class: "icon_image"%><br>
  </div>
  <div class="col my_page">
   <div class="row h2">
    <%= @user.name %>
   </div>
   <div class="row">
    <%= @user.detail%>
   </div>

   <% if @user.id === current_user.id %>
   <div class="row mt-5">
    <% @notifications.each do |notification| %>
    <dl class="text-left">
    <%= link_to user_path(notification.visitor) do %>
     <%= notification.visitor.name %>さんが
    <% end %>
    <% if notification.action=='dm' %>
        あなたにDMを送りました<br>
     <% end %>
    <% end %>
    </dl>
   </div>
   <% end %>

   <div class="row mt-5">
    <% unless @user.id == current_user.id %>
     <% if @haveRoom == true %>
       <%= link_to "ダイレクトメッセージ", room_path(@roomId), {class: "btn btn-secondary"} %>
     <% else %>
       <%= form_with model: @room, local: true do |f|%>
         <%= fields_for @RoomUser do |r| %>
           <%= r.hidden_field :user_id, value: @user.id %>
         <% end %>
         <%= f.submit  "チャットを始める" %>
       <% end %>
     <% end %>
    <% end %>
   </div>
   <div class="row">
    <% if @user.id == current_user.id %>
      <%= link_to "編集する", edit_user_path(current_user.id), class: "btn btn-secondary" %>
    <% end %>
   </div>
  </div>
 </div>

 <div class="border mt-5"></div>

<div class="mt-3 font-weight-bold h5">開催しているイベント</div>
 <div class="row bd-highlight mt-5">
 <% @events.each do | event | %>
 <div class="col-3 pb-5">
  <%= link_to event_path(event.id) do %>
   <div><%= attachment_image_tag event, :image, format: 'png', size: "200x200" %></div>
  <% end %>
  <div><%= link_to event.title, user_join_user_path(:event_id => event.id) %></div>
  <div>
   <%= event.date_from.strftime('%y年 %m月 %d日 %H時 %M分')%>
  </div>
  <div><%= event.location %> <%= event.city %> <%= event.park %></div>
 </div>
 <% end %>
</div>

<div class="border mt-5"></div>

<% if @user.id == current_user.id %>
  <div class="row">
   <div class="col-md-6">
   <div class="mt-3 font-weight-bold h5">イベント参加予定</div>
   <ul class="itemContrainer col-md-12 row d-flex flex-row bd-highlight mt-3">
    <% @event_joins.each do | join | %>
     <% if join.event.date_from > Date.today %>
      <li class="item col-md-12">
       <%= link_to join.event.title, event_path(join.event.id) %>
      </li>
     <% end %>
    <% end %>
   </ul>
  </div>

  <div class="col-md-6">
   <div class="mt-3 font-weight-bold h5">イベント参加履歴</div>
      <div class="itemContrainer col-md-12 row  d-flex flex-row bd-highlight mt-3">
      <% @event_joins.each do | join | %>
       <% if join.event.date_from < Date.today %>
        <div class="item col-md-12">
         <div><%= link_to join.event.title, event_path(join.event.id) %></div>
        </div>
       <% end %>
      <% end %>
     </div>
   </div>
  </div>
 <% end %>

app/views/users/user_join.html.erb
<div class="conteiner text-center font-weight-bold  mt-5">
  <div class="row">
    <div class="col h3">
      イベント参加者一覧
    </div>
  </div>
  <div class="row mt-5 ml-5">
    <% @users.each do | user | %>
    <dv class="col-3">
      <dl>
       <dt><%= link_to user.name, user_path(user.id) %></dt>
       <dd><%= attachment_image_tag user, :image, format: 'png', size: "500x400", class: "icon_image"%></dd>
      </dl>
    </dv>
    <% end %>
  </div>
</div>