config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get 'notifications/index'
  get 'homes/top'
  get 'homes/about'
  devise_for :users
  get "users/my_page"=>"users#index"
  resources :users, only: [:edit, :show, :update] do
    member do
      get :user_join
    end
  end
  resources :rooms
  resources :messages
  resources :events do
  collection do
    get 'search'
   end
  end

  resources :event_joins, only: [:create, :update]
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/event.rb
class Event < ApplicationRecord
   attachment :image
   enum location:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }
   belongs_to :user
   has_many :event_joins, foreign_key: :event_id, dependent: :destroy
  def joined(user)
    EventJoin.where(event_id: self.id, user_id: user.id, status: nil).exists?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events=Event.where('date_from >= ?', Date.today)
  end

  def new
    @event=Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id=current_user.id
    if @event.save
      redirect_to event_path(@event.id)
    else
    　render :new_event
    end
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to event_path(@event.id)
  end

  def show
    @event=Event.find(params[:id])
    @user = @event.user
    @event_join = EventJoin.find_by(user: current_user, event: @event) || EventJoin.new
    @events = Event.all
  end

  def edit
    @event=Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def search
    content = params[:content]
    @event = Event.locations.find {|key, value| key.match(/#{content}/)}
    if @event.blank?
     @events = Event.where('date_from >= ?', Date.today)
    else
     location_enum = @event[1]
    @events = Event.where(location: location_enum).where('date_from >= ?', Date.today)
    end
    render :index
  end

  private
  def search_for(content)
    Event.where(name: content)
  end


 def event_params
    params.require(:event).permit(:user_id, :title, :detail, :image, :date_from, :date_to, :location, :city, :park)
 end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div class="container">
  <div class="card user_form">
    <div class="card-body user">
      <div class="card-header font-weight-bold text-primary  form_title">イベント登録</div>
      <%= form_with model:@event,url: event_path(@event.id), local:true do |f| %>
      <table class="form font-weight-bold">
       <tr class="form-group">
        <td><label class="control-label">イベント名</label></td>
        <td><%= f.text_field :title, class: "form-control" %></td>
       </tr>
       
     　 <tr class="form-group">
        <td><label class="control-label">開始日時</label></td>
        <td><%= f.datetime_select :date_from, {use_month_numbers:true,minute_step:5}, class: 'form-control date' %></td>
       </tr>
       
       <tr class="form-group">
        <td><label class="control-label">終了日時</label></td>
        <td><%= f.datetime_select :date_to , {use_month_numbers:true}, class: 'form-control date' %></td>
       </tr>
       
       <tr class="form-group">
        <td><label class="control-label">県</label></td>
        <td><%= f.select :location, Event.locations.keys, {} %></td>
       </tr>
       
       <tr class="form-group">
        <td><label class="control-label">市町村</label></td>
        <td><%= f.text_field :city %></td>
       </tr>
       
       <tr class="form-group">
        <td><label class="control-label">公園名</label></td>
        <td><%= f.text_field :park %></td>
       </tr>
       
       <tr class="form-group">
        <td><label class="control-label">内容</label></td>
        <td><%= f.text_area :detail,size: "30x8" %></td>
       </tr>
       
       <tr class="form-group">
        <td><label class="control-label">イメージ写真</label></td>
        <td> <%= f.attachment_field :image %></td>
       </tr>
     </table>
     
     <div class="mt-5">
      <%= f.submit '変更保存', class: "btn btn-primary "%>
     </div>
    <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container mt-5">
 <div class="row pb-5">
  <div class="col text-center">
  <% if user_signed_in? %>
   <%= form_with url: search_events_path, method: :get do |form| %>
    <%= text_field_tag 'content' %>
    <%= submit_tag '検索' %>
   <% end %>
  <% end %>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
 <% @events.each do |event| %>
  <div class="col-4 col-mt-4 col-lg-4 col-sm-4 pb-5">
   <div>
    <%= link_to event_path(event.id) do %>
     <%= attachment_image_tag event, :image, format: 'png', size: "300x300" %>
    <% end %>
   </div>
   <div><%= event.title %></div>
   <div>
    <%= event.date_from.strftime('%y年 %m月 %d日 %H時 %M分')%>
   </div>
   <div><%= event.location %> <%= event.city %> <%= event.park %></div>
  </div>
 <% end %>
 </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="card user_form">
    <div class="card-body user">
      <div class="card-header font-weight-bold text-primary  form_title">イベント登録</div>
      <%= form_with model: @event, url: events_path, local:true do |f| %>
      <table class="form font-weight-bold">
       <tr class="form-group">
        <td><label class="control-label">イベント名</label></td>
      　<td><%= f.text_field :title, class: "form-control" %></td>
       </tr>
       <tr class="form-group">
        <td><label class="control-label">開始日時</label></td>
        <td><%= f.datetime_select :date_from, {use_month_numbers:true,minute_step:5}, class: 'form-control date' %></td>
       </tr>
       <tr class="form-group">
        <td><label class="control-label">終了日時</label></td>
        <td><%= f.datetime_select :date_to , {use_month_numbers:true}, class: 'form-control date' %></td>
       </tr>
       <tr class="form-group">
        <td><label class="control-label">県</label></td>
        <td><%= f.select :location, Event.locations.keys, {} %></td>
       </tr>
       <tr class="form-group">
        <td><label class="control-label">市町村</label></td>
        <td><%= f.text_field :city %></td>
       </tr>
       <tr class="form-group">
        <td><label class="control-label">公園名</label></td>
        <td><%= f.text_field :park %></td>
       </tr>
       <tr class="form-group">
        <td><label class="control-label">内容</label></td>
        <td><%= f.text_area :detail,size: "30x8" %></td>
       </tr>
       <tr class="form-group">
        <td><label class="control-label">イメージ写真</label></td>
       <td> <%= f.attachment_field :image %></td>
       </tr>
     </table>
     <div class="mt-5">
     <%= f.submit '新規登録', class: "btn btn-primary "%>
     </div>
    <% end %>
    </div>
  </div>
</div>

app/views/events/search.html.erb
<div class="itemContrainer d-flex flex-row bd-highlight mt-5">
 <% @events.each do |event| %>
  <div class="item mx-5">
   <div>
   <%= link_to event_path(event.id) do %>
    <%= attachment_image_tag event, :image, format: 'png', size: "300x300" %>
   <% end %>
   </div>
   <div><%= event.title %></div>
   <div>
    <%= event.date_from.strftime('%y年 %m月 %d日 %H時 %M分')%>
   </div>
   <div><%= event.location %> <%= event.city %> <%= event.park %></div>
  </div>
 <% end %>
</div>

app/views/events/show.html.erb
<div class="container">
 <div class="text-left">
  <div class="d-flex flex-column" style="width:500px;margin: 0 auto;">
   <div class="mb-5">
    <h1 class="text-center mt-5"><%= @event.title %></h1>
   </div>
   
   <dl>
     <dt class="text-center">場所</dt>
     <dd class="text-center">
      <%= @event.location %>
      <%= @event.city %>
      <%= @event.park %>
     </dd>
   </dl>
   <dl>
     <dt class="text-center">日時</dt>
     <dd class="text-center">
     <%= @event.date_from.strftime('%y年 %m月 %d日 %H時 %M分') %>
     ~
     <%= @event.date_to.strftime('%y年 %m月 %d日 %H %M分') %>
     </dd>
   </dl>
   <dl>
     <dt class="text-center">内容</dt>
     <dd class="text-center"><%= @event.detail %></dd>
   </dl>
   <dl>
     <dt class="text-center">開催者</dt>
     <dd class="text-center"><%= link_to @event.user.name,user_path(@user.id) %></dd>
   </dl>
   
   <div class="text-center">
   <%= attachment_image_tag @event, :image, format: 'png', size: "500x400" %><br>
   </div> 
   
   <div class="text-center mt-5">
    <% if @event.joined(current_user) == false && @user.id != current_user.id %>
      <%= link_to "参加する", "/event_joins/?event_id=#{@event.id}", method: :post, class: "btn btn-primary" %>
    <% end %>
    <% if @event.joined(current_user) %>
     <%= link_to "参加キャンセル", event_join_path(@event.id), method: :patch, "data-confirm" => "本当に参加キャンセルしますか？" %>
    <% end %>
   </div>
   
   <div class="mt-5 text-center">
     <% if @user.id === current_user.id %>
      <%= link_to "編集", edit_event_path(@event), class: "btn btn-primary mr-2" %>
      <%= link_to "削除", event_path(@event), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
     <% end %>
   </div>
  </div>
 </div>
</div><!-- container end -->